import type { Template } from "@reef/core";

/**
 * Seed templates the "Seed default templates" button commits when
 * `.reef/templates/` is empty. After seeding, these constants are no longer
 * read — the user edits the on-disk files instead.
 */
export const DEFAULT_ISSUE_TEMPLATES: readonly Template[] = [
  {
    name: "bug",
    label: "Bug report",
    description: "Reproducible defect with steps + expected vs. actual.",
    title_prefix: "Bug: ",
    priority: "high",
    default_labels: ["bug"],
    body: [
      "## Summary",
      "<one-sentence description of the bug>",
      "",
      "## Steps to reproduce",
      "1. ",
      "2. ",
      "3. ",
      "",
      "## Expected",
      "<what should happen>",
      "",
      "## Actual",
      "<what actually happens>",
      "",
      "## Environment",
      "- ",
    ].join("\n"),
  },
  {
    name: "feature",
    label: "Feature request",
    description: "Problem statement + proposed solution + acceptance.",
    title_prefix: "Feature: ",
    priority: "medium",
    default_labels: ["feature"],
    body: [
      "## Problem",
      "<the user pain or business goal>",
      "",
      "## Proposed solution",
      "<sketch of the approach>",
      "",
      "## Acceptance criteria",
      "- [ ] ",
      "- [ ] ",
      "",
      "## Out of scope",
      "- ",
    ].join("\n"),
  },
  {
    name: "task",
    label: "Task",
    description: "Scoped work item with goal + approach + notes.",
    priority: "medium",
    default_labels: [],
    body: [
      "## Goal",
      "<what we're trying to achieve>",
      "",
      "## Approach",
      "<high-level plan>",
      "",
      "## Notes",
      "- ",
    ].join("\n"),
  },
  {
    name: "tech-debt",
    label: "Tech debt",
    description: "Cleanup / refactor with risk + payoff.",
    title_prefix: "Tech debt: ",
    priority: "low",
    default_labels: ["tech-debt"],
    body: [
      "## Current state",
      "<what's there today and why it's painful>",
      "",
      "## Target state",
      "<what we want it to look like>",
      "",
      "## Risk",
      "<what could go sideways during the change>",
      "",
      "## Payoff",
      "<why now>",
    ].join("\n"),
  },
];
